### ISSUE TITLE
Программа для автоматического сбора ящиков в приложении

### ISSUE THREAD

**Issue by franchesko1437** [Rustamom/warfacePinsActivation#1]
Привет, а софт для автоматического просмотра рекламы и сбора ящиков имеется?)
[свяжись пожалуйста)](https://vk.com/eeeweqw9e85)

**Comment by Rustamom** [comment]
Не потянешь по цене

**Comment by franchesko1437** [comment]
> Не потянешь по цене
А вдруг ?
